import { ScenarioPackage } from './types';
import { Language, getLanguage } from '../i18n';
import { resolveAssetUrl } from '../utils/path';

export const HAREM_SCENARIO_JA: ScenarioPackage = {
  id: 'harem_choice',
  title: '放課後大波乱!? 一体誰が本命なのよ〜！',
  characters: [
    {
      id: 'girl_01',
      character: resolveAssetUrl('/models/aoi/aoi-school.vrm'),
      position: 'left',
    },
    {
      id: 'girl_04',
      character: resolveAssetUrl('/models/shion/shion-school.vrm'),
      position: 'center',
    },
    {
      id: 'girl_02',
      character: resolveAssetUrl('/models/emili/emili.vrm'),
      position: 'right',
    },
  ],
  bgmUrl: resolveAssetUrl('/bgm/bgm.mp3'),
  bgmVolume: 0.25,
  chapters: [
    {
      id: 'main',
      title: '本命決着裁判',
      scenes: [
        // Scene 1: アオイが真面目に切り出す
        {
          id: 'harem_intro_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '教室',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-corridor-far.avif'),
          voiceUrl: resolveAssetUrl('/voices/harem_intro_1.wav'),
          text: '「ねえ……今日こそ、ちゃんとハッキリさせてほしいの。」',
          cameraPosition: [-0.40, 1.35, 0.65],
          cameraTarget: [-0.65, 1.35, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.7,
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
          },
        },

        // Scene 2: エミリが横からズバッと叫ぶ！
        {
          id: 'harem_intro_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_intro_2.wav'),
          text: '「そうよ！ 誰にでも思わせぶりな態度取って……一体誰が本命なのよ〜！」',
          cameraPosition: [0.40, 1.30, 0.65],
          cameraTarget: [0.65, 1.30, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionEasing: 'gyuin',
          cameraTransitionDuration: 0.45,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.6,
              lookAtTarget: 'girl_02',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_02',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Angry.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'player',
            },
          },
        },

        // Scene 3: ダウナー少女シオンがため息まじりに一言
        {
          id: 'harem_intro_3',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_intro_3.wav'),
          text: '「……はぁ。めんどくさ。私まで巻き込まないでほしいんだけど。……で？ 誰なわけ？」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_04',
            },
          },
        },

        // Scene 4: アオイが引かずに詰め寄る（3人全員映す構図）
        {
          id: 'harem_intro_4',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_intro_4.wav'),
          text: '「私達3人の中で、あなたの本当の気持ち……教えて？」',
          cameraPosition: [0, 1.20, 1.85],
          cameraTarget: [0, 1.20, -0.4],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              effectText: 'doki',
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.7,
              lookAtTarget: 'player',
            },
          },
        },

        // Scene 5: 3人が一斉にあなたを見つめて選択肢！（カメラを離してエミリの見切れ防止＆シオンは通常待機）
        {
          id: 'harem_choice',
          speaker: '3人',
          dialogueTarget: 'player',
          location: '教室',
          text: '（3人からの視線が突き刺さる……！ 一体誰を選ぶ！？）',
          cameraPosition: [0, 1.20, 1.95],
          cameraTarget: [0, 1.20, -0.4],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.7,
          cameraPreset: 'hold',
          choiceDelaySec: 0.8,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headWeight: 0.9,
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headWeight: 0.9,
            },
          },
          choices: [
            {
              text: '💙 アオイが本命だよ！',
              flag: 'choice_aoi',
              goto: 'route_aoi_1',
              effectText: 'doki',
            },
            {
              text: '💛 エミリが本命だよ！',
              flag: 'choice_emily',
              goto: 'route_emily_1',
              effectText: 'yatta',
            },
            {
              text: '🖤 シオンが本命だよ！',
              flag: 'choice_shion',
              goto: 'route_shion_1',
              effectText: 'kirakira',
            },
            {
              text: '💥 3人とも大好きだーっ！！（選べない）',
              flag: 'choice_all',
              goto: 'route_all_1',
              effectText: 'iraira',
            },
          ],
        },

        // ==========================================
        // Route 1: アオイ本命
        // ==========================================
        {
          id: 'route_aoi_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_aoi_1.wav'),
          text: '「えっ……！？ ほ、本当に私……！？ 夢じゃないよね……っ！？」',
          cameraPosition: [-0.40, 1.35, 0.65],
          cameraTarget: [-0.65, 1.35, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'doki',
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 1.0,
              lookAtTarget: 'girl_01',
            },
          },
        },
        {
          id: 'route_aoi_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_aoi_2.wav'),
          text: '「ちょっとー！ なんでアオイなのよー！ 私のほうが絶対カワイイのにー！」',
          cameraPosition: [0.40, 1.30, 0.65],
          cameraTarget: [0.65, 1.30, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_02',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Angry.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'route_aoi_3',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_aoi_3.wav'),
          text: '「ふぁ……。あっそ。お熱いことで。じゃ、決まったなら私帰って寝るね。」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          goto: 'harem_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_04',
            },
          },
        },

        // ==========================================
        // Route 2: エミリ本命
        // ==========================================
        {
          id: 'route_emily_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_emily_1.wav'),
          text: '「やったーっ！ やっぱり私が一番でしょ♪ 見たかアオイ〜！」',
          cameraPosition: [0.40, 1.30, 0.65],
          cameraTarget: [0.65, 1.30, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 1.0,
              lookAtTarget: 'girl_02',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'route_emily_2',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_emily_2.wav'),
          text: '「うそ……っ！ 私じゃなかったの……！？ もう、バカバカ、知らないっ！」',
          cameraPosition: [-0.40, 1.35, 0.65],
          cameraTarget: [-0.65, 1.35, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Angry.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_01',
            },
          },
        },
        {
          id: 'route_emily_3',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_emily_3.wav'),
          text: '「……はいはい。お似合いなんじゃない？ 騒がしいカップルの誕生だね。」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          goto: 'harem_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_04',
            },
          },
        },

        // ==========================================
        // Route 3: シオン（ダウナー少女）本命
        // ==========================================
        {
          id: 'route_shion_1',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_shion_1.wav'),
          text: '「……は？ ……え、な、何言ってんの……？ 私なんか選んで……後悔しても知らないから……っ。」',
          cameraPosition: [0, 1.25, 0.70],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 1.0,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.9,
              effectText: 'doki',
              lookAtTarget: 'player',
              faceTexture: '/textures/girl_face_blush.png',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 1.0,
              lookAtTarget: 'girl_04',
            },
          },
        },
        {
          id: 'route_shion_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_shion_2.wav'),
          text: '「ええええーっ！？ まさかのシオン！？ なんでよーっ！？」',
          cameraPosition: [0.40, 1.30, 0.65],
          cameraTarget: [0.65, 1.30, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_02',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Angry.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'girl_04',
            },
          },
        },
        {
          id: 'route_shion_3',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_shion_3.wav'),
          text: '「し、シオンだったの……？ でも……シオン、すっごく顔真っ赤だよ……？」',
          cameraPosition: [-0.40, 1.35, 0.65],
          cameraTarget: [-0.65, 1.35, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          goto: 'harem_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.8,
              effectText: 'doki',
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_04',
            },
          },
        },

        // ==========================================
        // Route 4: 全員大好き（修羅場・大波乱）
        // ==========================================
        {
          id: 'route_all_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_all_1.wav'),
          text: '「はあぁぁ！？ 一番言っちゃいけない最低なセリフ出たー！！」',
          cameraPosition: [0.40, 1.30, 0.65],
          cameraTarget: [0.65, 1.30, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.45,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Angry.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'route_all_2',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_all_2.wav'),
          text: '「サイテー……。本当に反省してよね！ もうみんなで絶交だから！」',
          cameraPosition: [-0.40, 1.35, 0.65],
          cameraTarget: [-0.65, 1.35, -0.45],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          focusLines: true,
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Punching.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'iraira',
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'route_all_3',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          dialogueTarget: 'player',
          location: '教室',
          voiceUrl: resolveAssetUrl('/voices/harem_all_3.wav'),
          text: '「……救いようがないね。エナドリ奢ってもらっても……許さないから。」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          goto: 'harem_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'angry',
              expressionWeight: 0.9,
              lookAtTarget: 'player',
            },
          },
        },

        // ==========================================
        // Ending: 共通エピローグ（3人全体を引いて映し、シオンはポーズなし）
        // ==========================================
        {
          id: 'harem_ending',
          speaker: 'ナレーション',
          dialogueTarget: 'player',
          location: '教室',
          text: 'こうして、放課後のドタバタ本命裁判は幕を閉じた……（？） あなたと3人の騒がしい青春はまだまだ続きそうだ。',
          cameraPosition: [0, 1.20, 1.95],
          cameraTarget: [0, 1.20, -0.4],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.8,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_04: {
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'player',
            },
          },
        },
      ],
    },
  ],
};

export function getHaremConversationScenario(lang: Language = getLanguage()): ScenarioPackage {
  // Currently JA is the primary scenario
  return HAREM_SCENARIO_JA;
}
