import { ScenarioPackage } from './types';
import { Language, getLanguage } from '../i18n';
import { resolveAssetUrl } from '../utils/path';

export const PRIVATE_DATE_SCENARIO_JA: ScenarioPackage = {
  id: 'private_date',
  title: '休日デート〜私服のエミリと街歩き〜',
  characters: [
    {
      id: 'girl_02',
      character: resolveAssetUrl('/models/emili/emili-private.vrm'),
      position: 'center',
      rotationY: 0,
    },
    {
      id: 'girl_04',
      character: resolveAssetUrl('/models/shion/shion-private.vrm'),
      position: 'right',
      rotationY: -0.22,
    },
    {
      id: 'girl_01',
      character: resolveAssetUrl('/models/aoi/aoi-private.vrm'),
      position: 'right',
      rotationY: -0.22,
    },
  ],
  bgmUrl: resolveAssetUrl('/bgm/bgm.mp3'),
  bgmVolume: 0.22,
  chapters: [
    {
      id: 'main',
      title: '休日デートの1日',
      scenes: [
        // ============================================================
        // 1. 自室でソワソワと準備、呼び鈴が鳴る（朝）
        // ============================================================
        {
          id: 'prep_1',
          speaker: 'あなた',
          location: '自分の部屋',
          scenePreset: 'bright_indoor',
          background: resolveAssetUrl('/textures/myroom_far.avif'),
          text: '（よし、準備完了！ エミリとの初めての休日デート……なんだかソワソワするな。）',
          cameraPosition: [0, 1.25, 1.1],
          cameraTarget: [0, 1.2, 0],
          cameraZoom: 'none',
          cameraTransitionDuration: 0,
          avatars: {
            girl_02: { visible: false },
            girl_04: { visible: false },
            girl_01: { visible: false },
          },
        },
        {
          id: 'prep_2',
          speaker: 'あなた',
          location: '自分の部屋',
          scenePreset: 'bright_indoor',
          background: resolveAssetUrl('/textures/myroom_far.avif'),
          seUrl: resolveAssetUrl('/se/door_chime.mp3'),
          seLoop: false,
          text: '（ピンポーン♪ ……あっ、呼び鈴だ！ エミリが玄関まで迎えに来てくれたみたいだ！）',
          cameraPosition: [0, 1.25, 1.1],
          cameraTarget: [0, 1.2, 0],
          cameraZoom: 'none',
          avatars: {
            girl_02: { visible: false },
            girl_04: { visible: false },
            girl_01: { visible: false },
          },
          screenTransition: 'interlude',
        },

        // ============================================================
        // 2. エミリが玄関まで迎えに来てデートに出発（朝）
        // ============================================================
        {
          id: 'door_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '玄関前',
          scenePreset: 'day_outdoor',
          background: resolveAssetUrl('/textures/apartment_door_far.avif'),
          voiceUrl: resolveAssetUrl('/voices/date_emili_01.wav'),
          text: '「おはよー！ 待たせちゃった？ 今日の私服……どうかな、似合ってる？」',
          cameraPosition: [0, 1.25, 0.72],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              effectText: 'kirakira',
              lookAtTarget: 'player',
            },
            girl_04: { visible: false },
            girl_01: { visible: false },
          },
        },
        {
          id: 'door_choice',
          speaker: '',
          text: '',
          location: '玄関前',
          scenePreset: 'day_outdoor',
          cameraPosition: [0, 1.25, 0.72],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          choiceDelaySec: 0,
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.85,
              lookAtTarget: 'player',
            },
          },
          choices: [
            {
              text: 'すっごく似合ってるよ、可愛い！',
              goto: 'door_choice_1',
              effectText: 'doki',
            },
            {
              text: 'いつもと違って大人っぽいね',
              goto: 'door_choice_2',
              effectText: 'kirakira',
            },
          ],
        },
        {
          id: 'door_choice_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '玄関前',
          voiceUrl: resolveAssetUrl('/voices/date_emili_02a.wav'),
          text: '「ほんと！？ えへへ……嬉しいな！ 実は今日のために色々悩んで選んだんだ♪」',
          cameraZoom: 'speaker_close',
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'doki',
              lookAtTarget: 'player',
            },
          },
          goto: 'door_depart',
        },
        {
          id: 'door_choice_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '玄関前',
          voiceUrl: resolveAssetUrl('/voices/date_emili_02b.wav'),
          text: '「大人っぽい！？ ……そ、そうかな？ えへへ、ちょっと照れちゃうけど嬉しい♪」',
          cameraZoom: 'speaker_close',
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.95,
              faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
              lookAtTarget: 'player',
            },
          },
          goto: 'door_depart',
        },
        {
          id: 'door_depart',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '玄関前',
          voiceUrl: resolveAssetUrl('/voices/date_emili_03.wav'),
          text: '「それじゃ、今日のデート……しゅっぱーつ！」',
          cameraPosition: [0, 1.25, 0.85],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'medium',
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
              lookAtTarget: 'player',
            },
          },
          screenTransition: 'fade_black',
        },

        // ============================================================
        // 3. 歩き会話シナリオと同じ感じでエミリと歩きながら会話（朝）
        // ============================================================
        {
          id: 'walk_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '休日の並木道',
          text: '「こうして並んで歩くの、なんだかドキドキしちゃうね……！ お天気も最高だし♪」',
          voiceUrl: resolveAssetUrl('/voices/date_emili_04.wav'),
          seUrl: resolveAssetUrl('/se/walking.mp3'),
          seLoop: true,
          scrollingBackground: {
            enabled: true,
            textureUrl: resolveAssetUrl('/textures/town_far.avif'),
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.88,
          cameraTarget: [0, 1.30, 0],
          cameraPreset: 'hold',
          cameraTransitionDuration: 0,
          cameraTransitionEasing: 'cut',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Walking.fbx'),
              expression: 'relax',
              expressionWeight: 0.85,
              position: [0.12, 0, -0.4],
              rotationY: -0.22,
              headOffset: [0, -0.12],
            },
            girl_04: { visible: false },
            girl_01: { visible: false },
          },
        },
        {
          id: 'walk_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '休日の並木道',
          text: '「ねえねえ、まずはどこから行く？ 行きたいお店、いっぱいチェックしてきたんだ〜！」',
          voiceUrl: resolveAssetUrl('/voices/date_emili_05.wav'),
          scrollingBackground: {
            enabled: true,
            textureUrl: resolveAssetUrl('/textures/town_far.avif'),
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.88,
          cameraTarget: [0, 1.30, 0],
          cameraPreset: 'hold',
          cameraTransitionDuration: 0,
          cameraTransitionEasing: 'cut',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Walking.fbx'),
              expression: 'happy',
              expressionWeight: 0.95,
              position: [0.12, 0, -0.4],
              rotationY: -0.22,
              lookAtCamera: false,
              headLookAtCamera: false,
              headOffset: [0, -0.12],
            },
          },
        },
        {
          id: 'walk_3',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '休日の並木道',
          text: '「……ふふっ、私の横顔ばっかり見てどうしたの？ 照れちゃうじゃん！」',
          voiceUrl: resolveAssetUrl('/voices/date_emili_06.wav'),
          scrollingBackground: {
            enabled: true,
            textureUrl: resolveAssetUrl('/textures/town_far.avif'),
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.88,
          cameraTarget: [0, 1.30, 0],
          cameraPreset: 'hold',
          cameraTransitionDuration: 0,
          cameraTransitionEasing: 'cut',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Walking.fbx'),
              expression: 'relax',
              expressionWeight: 1.0,
              faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
              position: [0.12, 0, -0.4],
              rotationY: -0.25,
              lookAtCamera: true,
              headOffset: [0, -0.12],
              effectText: 'doki',
            },
          },
          screenTransition: 'interlude',
        },

        // ============================================================
        // 4. 歩き会話終わって街でシオンと出会う、会話してシオンとは別れる（昼）
        // ============================================================
        {
          id: 'shion_1',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          location: '街角の広場',
          scenePreset: 'day_outdoor',
          background: resolveAssetUrl('/textures/town_far.avif'),
          voiceUrl: resolveAssetUrl('/voices/date_shion_01.wav'),
          text: '「……ん？ あんた達、こんなところで何してんの。……あー、デート？ ふーん。」',
          cameraPosition: [0.38, 1.25, -0.48],
          cameraTarget: [0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionEasing: 'smooth',
          cameraTransitionDuration: 0.5,
          scrollingBackground: { enabled: false },
          avatars: {
            girl_02: {
              visible: true,
              position: [-0.38, -0.1, -1.15],
              rotationY: 0.22,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.8,
              faceTexture: undefined,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              visible: true,
              position: [0.38, -0.1, -1.15],
              rotationY: -0.22,
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'neutral',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
            girl_01: { visible: false },
          },
        },
        {
          id: 'shion_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '街角の広場',
          voiceUrl: resolveAssetUrl('/voices/date_emili_07.wav'),
          text: '「シ、シオン！？ なんでこんなところに……！ べ、別にデートじゃないし……あ、いやデートだけど！」',
          cameraPosition: [-0.38, 1.25, -0.48],
          cameraTarget: [-0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionEasing: 'gyuin',
          cameraTransitionDuration: 0.4,
          focusLines: true,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'angry',
              expressionWeight: 1.0,
              effectText: 'wanawana',
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              visible: true,
              motion: resolveAssetUrl('/animations/Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'shion_3',
          speaker: 'シオン',
          speakerCharacterId: 'girl_04',
          location: '街角の広場',
          voiceUrl: resolveAssetUrl('/voices/date_shion_02.wav'),
          text: '「別に邪魔する気はないよ。私、そこの本屋行くだけだし。私服……ふたりとも気合い入ってんね。じゃ、お邪魔虫は退散しまーす。」',
          cameraPosition: [0.38, 1.25, -0.48],
          cameraTarget: [0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionEasing: 'smooth',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.7,
              lookAtTarget: 'girl_04',
            },
            girl_04: {
              visible: true,
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'shion_4',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '街角の広場',
          voiceUrl: resolveAssetUrl('/voices/date_emili_08.wav'),
          text: '「もーっ！ シオンったら急に現れてからかうんだから！ ……ふぅ、びっくりした。気を取り直して行こっ！」',
          cameraPosition: [0, 1.25, 0.7],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.85,
              lookAtTarget: 'player',
            },
            girl_04: { visible: false },
          },
          screenTransition: 'interlude',
        },

        // ============================================================
        // 5. カフェに入る、アオイと出会う（昼）
        // ============================================================
        {
          id: 'cafe_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          location: 'テラスカフェ',
          scenePreset: 'day_outdoor',
          background: resolveAssetUrl('/textures/cafe_far.avif'),
          voiceUrl: resolveAssetUrl('/voices/date_aoi_01.wav'),
          text: '「あ……！ ふたりとも、こんにちは！ こんな素敵なカフェで会うなんて、すごい偶然だね！」',
          cameraPosition: [0.38, 1.25, -0.48],
          cameraTarget: [0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              position: [-0.38, -0.1, -1.15],
              rotationY: 0.22,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_01: {
              visible: true,
              position: [0.38, -0.1, -1.15],
              rotationY: -0.22,
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_02',
            },
            girl_04: { visible: false },
          },
        },
        {
          id: 'cafe_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: 'テラスカフェ',
          voiceUrl: resolveAssetUrl('/voices/date_emili_09.wav'),
          text: '「アオイ！ アオイも私服でお買い物？ すっごく似合ってて可愛い〜！」',
          cameraPosition: [-0.38, 1.25, -0.48],
          cameraTarget: [-0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'kirakira',
              lookAtTarget: 'girl_01',
            },
            girl_01: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'cafe_3',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          location: 'テラスカフェ',
          voiceUrl: resolveAssetUrl('/voices/date_aoi_02.wav'),
          text: '「ありがとうエミリ！ エミリのワンピースもすごくお洒落だよ。……ふたりで、お出かけ中だったんだ？」',
          cameraPosition: [0.38, 1.25, -0.48],
          cameraTarget: [0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_01: {
              visible: true,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'cafe_4',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: 'テラスカフェ',
          voiceUrl: resolveAssetUrl('/voices/date_emili_10.wav'),
          text: '「うん！ ちょっと休憩にお茶しよって話してて。アオイも一緒にどう？」',
          cameraPosition: [-0.38, 1.25, -0.48],
          cameraTarget: [-0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 0.9,
              lookAtTarget: 'girl_01',
            },
            girl_01: {
              visible: true,
              faceTexture: undefined,
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'cafe_5',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          location: 'テラスカフェ',
          voiceUrl: resolveAssetUrl('/voices/date_aoi_03.wav'),
          text: '「ふふ、誘ってくれてありがとう。でも私はこれから約束があるから……ふたりでゆっくり楽しんできてね？」',
          cameraPosition: [0.38, 1.25, -0.48],
          cameraTarget: [0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              lookAtTarget: 'girl_01',
            },
            girl_01: {
              visible: true,
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'happy',
              expressionWeight: 0.95,
              lookAtTarget: 'girl_02',
            },
          },
        },
        {
          id: 'cafe_6',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: 'テラスカフェ',
          voiceUrl: resolveAssetUrl('/voices/date_emili_11.wav'),
          text: '「そっか、残念！ また学校でゆっくりお話しよ！」',
          cameraPosition: [-0.38, 1.25, -0.48],
          cameraTarget: [-0.38, 1.25, -1.15],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              lookAtTarget: 'girl_01',
            },
            girl_01: { visible: false },
          },
          screenTransition: 'fade_black',
        },

        // ============================================================
        // 6. 最後に公園で会話（夕）
        // ============================================================
        {
          id: 'park_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          background: resolveAssetUrl('/textures/modern-park-far.avif'),
          voiceUrl: resolveAssetUrl('/voices/date_emili_12.wav'),
          text: '「ふぅ……！ 今日一日、すっごく楽しかったな。あっという間に夕方になっちゃったね。」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.6,
          avatars: {
            girl_02: {
              visible: true,
              position: 'center',
              rotationY: 0,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
              faceTexture: undefined,
              lookAtTarget: 'player',
            },
            girl_01: { visible: false },
            girl_04: { visible: false },
          },
        },
        {
          id: 'park_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          voiceUrl: resolveAssetUrl('/voices/date_emili_13.wav'),
          text: '「街でシオンにからかわれたり、カフェでアオイに会ったり……賑やかだったけど……」',
          cameraZoom: 'speaker_close',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 0.85,
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'park_3',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          voiceUrl: resolveAssetUrl('/voices/date_emili_14.wav'),
          text: '「でもね……あなたと過ごした今日の時間、私にとってすごく特別だったよ。」',
          cameraPosition: [0, 1.28, 0.62],
          cameraTarget: [0, 1.28, -0.3],
          cameraZoom: 'speaker_close',
          cameraTransitionDuration: 0.5,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
              effectText: 'doki',
              lookAtTarget: 'player',
            },
          },
        },
        {
          id: 'park_choice',
          speaker: '',
          text: '',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          cameraPosition: [0, 1.28, 0.62],
          cameraTarget: [0, 1.28, -0.3],
          cameraZoom: 'speaker_close',
          choiceDelaySec: 0,
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.95,
              faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
              lookAtTarget: 'player',
            },
          },
          choices: [
            {
              text: '俺もすごく楽しかった、ありがとう',
              goto: 'park_choice_1',
              effectText: 'kirakira',
            },
            {
              text: 'また二人でデートしようね',
              goto: 'park_choice_2',
              effectText: 'doki',
            },
          ],
        },
        {
          id: 'park_choice_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          voiceUrl: resolveAssetUrl('/voices/date_emili_15a.wav'),
          text: '「えへへ、そう言ってもらえて幸せだな……♪」',
          cameraZoom: 'speaker_close',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'kirakira',
              lookAtTarget: 'player',
            },
          },
          goto: 'park_ending',
        },
        {
          id: 'park_choice_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          voiceUrl: resolveAssetUrl('/voices/date_emili_15b.wav'),
          text: '「うんっ……！ 絶対、またデートしてね。約束だよ♪」',
          cameraZoom: 'speaker_close',
          dreamBackground: 'heart',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
              lookAtTarget: 'player',
            },
          },
          goto: 'park_ending',
        },
        {
          id: 'park_ending',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          location: '夕暮れの公園',
          scenePreset: 'evening_park',
          voiceUrl: resolveAssetUrl('/voices/date_emili_16.wav'),
          text: '「今日は本当にありがとう！ 来週も……楽しみにしてるね！」',
          cameraPosition: [0, 1.25, 0.75],
          cameraTarget: [0, 1.25, -0.3],
          cameraZoom: 'speaker_close',
          dreamBackground: 'heart',
          avatars: {
            girl_02: {
              visible: true,
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
            },
          },
        },
      ],
    },
  ],
};

export function getPrivateDateScenario(lang: Language = 'ja'): ScenarioPackage {
  return PRIVATE_DATE_SCENARIO_JA;
}
