import { ScenarioPackage } from './types';
import { resolveAssetUrl } from '../utils/path';
import { Language, getLanguage } from '../i18n';

export const ROOFTOP_NAP_SCENARIO_JA: ScenarioPackage = {
  id: 'rooftop_nap',
  title: '屋上の昼寝と、覗き込みハプニング',
  bgmUrl: '/bgm/bgm.mp3',
  bgmVolume: 0.3,
  chapters: [
    {
      id: 'main',
      title: 'ぽかぽか陽気の屋上',
      scenes: [
        // Scene 1: 導入 - 屋上の床に寝転がって昼寝
        {
          id: 'rooftop_intro_1',
          speaker: '主人公',
          location: '学校・屋上',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '（ぽかぽか陽気のお昼休み。あまりに風が心地よくて、屋上の隅で直に寝転がってうとうとしていた……）',
          character: 'girl_01',
          live2d: false,
          avatar: {
            visible: false,
          },
          cameraZoom: 'wide',
          cameraTransitionEasing: 'smooth',
          cameraTransitionDuration: 1.0,
          cameraPreset: 'hold',
        },
        // Scene 2: アオイが見つける
        {
          id: 'rooftop_intro_2',
          speaker: 'アオイ',
          location: '学校・屋上',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「あれ？ こんなところで誰か寝転がってると思ったら……きみだったんだ！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_01.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            visible: true,
            motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
            expression: 'happy',
            expressionWeight: 0.8,
            position: [0, 0, -0.9],
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.5,
          cameraTransitionEasing: 'smooth',
          cameraTransitionDuration: 0.9,
          cameraPreset: 'hold',
        },
        // Scene 3: いたずらを企む
        {
          id: 'rooftop_walk_3',
          speaker: 'アオイ',
          location: '学校・屋上',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「ふふっ、すっごく気持ちよさそうな寝顔。ちょっといたずらして驚かせちゃおうかな」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_02.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            visible: true,
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
            expression: 'relaxed',
            expressionWeight: 0.9,
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.35,
          cameraTransitionEasing: 'gyuin',
          cameraTransitionDuration: 1.2,
          cameraPreset: 'pushIn',
          cameraStrength: 0.4,
        },
        // Scene 4: Live2Dモードへ切り替え（しゃがみこんで顔を覗き込む）
        {
          id: 'rooftop_live2d_4',
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「……ねぇ。いつまで寝てるの？ 起こしちゃって悪いんだけど……起きて？」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_03.wav'),
          character: 'girl_01',
          live2d: true,
          cameraZoom: 'speaker_close',
          cameraDistance: 0.7,
          cameraPreset: 'hold',
        },
        // Scene 5: 主人公が目を覚まして視線が合う
        {
          id: 'rooftop_live2d_5',
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「……あ、起きた。ふふ、おはよう。……ん？ なにじっと見てるの？ 私の顔、変……？」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_04.wav'),
          character: 'girl_01',
          live2d: true,
          cameraZoom: 'speaker_close',
          cameraDistance: 0.7,
          cameraPreset: 'hold',
        },
        // Scene 6: スカートでしゃがんでいることに気づいて激しく赤面！
        {
          id: 'rooftop_live2d_6',
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「……えっ？ ちょっと、待って……どこ見て――きゃあっ！？ わ、わたし、スカートでこんな屈み方……っ！！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_05.wav'),
          character: 'girl_01',
          live2d: true,
          avatar: {
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
          },
          cameraZoom: 'speaker_close',
          cameraDistance: 0.65,
          cameraPreset: 'punchIn',
          cameraStrength: 0.9,
        },
        // Scene 7: Live2D終了・パッと飛び退いて立ち上がり激怒！（セリフのみ・選択肢なし）
        {
          id: 'rooftop_angry_7',
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「ば、バカっ！ 見たでしょ今！？ 絶対見えたよね……！？ 最低ぇっ、変態っ！！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_06.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            visible: true,
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Angry.fbx'),
            expression: 'angry',
            expressionWeight: 1.0,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
            effectText: 'iraira',
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.35,
          cameraTransitionEasing: 'gyuin',
          cameraTransitionDuration: 0.5,
          cameraPreset: 'punchIn',
          cameraStrength: 1.0,
        },

        // Scene 8: 選択肢専用シーン（規則遵守: セリフ・ナレーション完全排除、text: ''）
        {
          id: 'rooftop_choice_8',
          speaker: '',
          text: '',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            visible: true,
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Angry.fbx'),
            expression: 'angry',
            expressionWeight: 1.0,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.35,
          cameraPreset: 'hold',
          choiceDelaySec: 0.3,
          choices: [
            {
              text: '「ごめん！ でも……すごく綺麗だったから……」',
              flag: 'rooftop_cute',
              goto: 'rooftop_route_1',
              effectText: 'doki',
            },
            {
              text: '「見てない！ 空の雲の形を見てただけ！」',
              flag: 'rooftop_sky',
              goto: 'rooftop_route_2',
              effectText: 'asease',
            },
            {
              text: '「……白でした」',
              flag: 'rooftop_white',
              goto: 'rooftop_route_3',
              effectText: 'gaan',
            },
          ],
        },

        // -------------------------------------------------------------
        // 選択肢1: 「綺麗だったから」
        // -------------------------------------------------------------
        {
          id: 'rooftop_route_1',
          conditions: ['rooftop_cute'],
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「〜〜っバカ！ そういうこと堂々と言わないでよ……！ 余計に恥ずかしいじゃん……！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_ans_1.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
            expression: 'surprised',
            expressionWeight: 0.9,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
            effectText: 'doki',
          },
          cameraZoom: 'speaker_close',
          cameraDistance: 1.1,
          cameraPreset: 'orbitRightHalf',
          cameraStrength: 0.6,
          goto: 'rooftop_ending',
        },

        // -------------------------------------------------------------
        // 選択肢2: 「雲の形を見てただけ」
        // -------------------------------------------------------------
        {
          id: 'rooftop_route_2',
          conditions: ['rooftop_sky'],
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「大嘘つき！ 目線が完全に下向いてたの、バッチリ見えてたんだからね……！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_ans_2.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Angry.fbx'),
            expression: 'angry',
            expressionWeight: 1.0,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
            effectText: 'gaan',
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.2,
          cameraPreset: 'pushIn',
          cameraStrength: 0.8,
          goto: 'rooftop_ending',
        },

        // -------------------------------------------------------------
        // 選択肢3: 「白でした」
        // -------------------------------------------------------------
        {
          id: 'rooftop_route_3',
          conditions: ['rooftop_white'],
          speaker: 'アオイ',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '「堂々と報告するなーーっ！！ ほんっと信じられない……！ バカバカバカッ！」',
          voiceUrl: resolveAssetUrl('/voices/rooftop_ans_3.wav'),
          character: 'girl_01',
          live2d: false,
          avatar: {
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Punching.fbx'),
            expression: 'angry',
            expressionWeight: 1.0,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
            effectText: 'iraira',
          },
          cameraTarget: [0, 0.98, -0.9],
          cameraZoom: 'speaker_close',
          cameraDistance: 1.15,
          cameraPreset: 'punchIn',
          cameraStrength: 0.9,
          goto: 'rooftop_ending',
        },

        // -------------------------------------------------------------
        // エピローグ
        // -------------------------------------------------------------
        {
          id: 'rooftop_ending',
          speaker: '主人公',
          location: '学校・屋上',
          screenTransition: 'none',
          scenePreset: 'day_school',
          background: resolveAssetUrl('/textures/school-rooftop-far.avif'),
          text: '（……真っ赤な顔で怒るアオイに平謝りしながら、騒がしくも照れくさいお昼休みの時間は過ぎていった。【シナリオ終了】）',
          character: 'girl_01',
          live2d: false,
          avatar: {
            position: [0, 0, -0.9],
            motion: resolveAssetUrl('/animations/Female Standing Pose.fbx'),
            expression: 'relaxed',
            expressionWeight: 0.7,
            faceTexture: resolveAssetUrl('/textures/girl_face_blush.png'),
          },
          cameraZoom: 'speaker',
          cameraDistance: 1.35,
          cameraPreset: 'hold',
        },
      ],
    },
  ],
};

export function getRooftopNapScenario(lang: Language = getLanguage()): ScenarioPackage {
  return ROOFTOP_NAP_SCENARIO_JA;
}
