import { ScenarioPackage } from './types';
import { Language, getLanguage } from '../i18n';

export const TOWN_WALK_SCENARIO_JA: ScenarioPackage = {
  id: 'town_walk',
  title: '放課後の並木道 〜君と歩く帰り道〜',
  bgmUrl: '/bgm/bgm.mp3',
  bgmVolume: 0.3,
  chapters: [
    {
      id: 'main',
      title: '街の散歩道',
      scenes: [
        // ============================================================
        // 前半: 歩きながらの会話パート
        // ・アオイと自キャラが並んで街を歩く
        // ・自キャラは横にいるアオイを見ている (左側からアオイへZoomした構図)
        // ・背景は town_far.png、2枚の板が無限ループで横スライド
        // ・アオイにフォーカスして背景はアニメ調にぼかす
        // ・アオイは歩行モーション (Walking)
        // ============================================================
        {
          id: 'walk_1',
          speaker: 'アオイ',
          location: '放課後の並木道',
          text: '「放課後、こうして一緒に並んで歩いて帰るの……なんだか久しぶりだね！」',
          voiceUrl: '/voices/town_walk_1.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.85,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          cameraPreset: 'pushIn',
          cameraStrength: 0.2,
          cameraTransitionDuration: 0,
          cameraTransitionEasing: 'cut',
        },
        {
          id: 'walk_2',
          speaker: 'アオイ',
          location: '放課後の並木道',
          text: '「この並木道、街並みも綺麗だし、風がふわっと抜けてすごく気持ちいいな〜」',
          voiceUrl: '/voices/town_walk_2.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.95,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.88,
          cameraPreset: 'hold',
          cameraTransitionDuration: 0.7,
        },
        {
          id: 'walk_3',
          speaker: 'アオイ',
          location: '放課後の並木道',
          text: '「ねえ、聞いてる？ ……ふふっ、私の横顔ばっかり見て、どうしたの？」',
          voiceUrl: '/voices/town_walk_3.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0.12, 0, 0],
            rotationY: -0.25,
            effectText: 'doki',
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_extreme_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.82,
          cameraPreset: 'pushIn',
          cameraStrength: 0.5,
          choices: [
            {
              text: '「アオイが楽しそうだったから、つい見とれてた」',
              flag: 'admire_her',
              goto: 'walk_route_admire',
              effectText: 'doki',
            },
            {
              text: '「この先に新しくできたお店の話を思い出してさ」',
              flag: 'talk_shop',
              goto: 'walk_route_shop',
              effectText: 'kirakira',
            },
          ],
        },

        // --- ルートA: 見とれていた ---
        {
          id: 'walk_route_admire',
          speaker: 'アオイ',
          location: '放課後の並木道',
          text: '「も、もう〜！ 急にそういうこと言うんだから……ちょっと照れるじゃん」',
          voiceUrl: '/voices/town_walk_admire.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            faceTexture: '/textures/girl_face_blush.png',
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          goto: 'walk_transition_stop',
        },

        // --- ルートB: お店の話 ---
        {
          id: 'walk_route_shop',
          speaker: 'アオイ',
          location: '放課後の並木道',
          text: '「あ、知ってた！？ 私もちょうどその話しようと思ってたんだよね！」',
          voiceUrl: '/voices/town_walk_shop.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.95,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          goto: 'walk_transition_stop',
        },

        // ============================================================
        // シーン切り替え（立ち止まり）: アオイが看板を見つけて立ち止まる
        // ・背景は通常の1枚背景（固定位置）に戻し、スライド板を非表示
        // ============================================================
        {
          id: 'walk_transition_stop',
          speaker: 'アオイ',
          location: '街の広場・カフェ前',
          text: '「あっ、見て見て！ ほら、あそこの看板……ちょっと止まって！」',
          voiceUrl: '/voices/town_walk_stop.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Standing Greeting.fbx',
            expression: 'relaxed',
            expressionWeight: 0.85,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'medium',
          cameraStartAngle: 'front',
          cameraDistance: 1.25,
          cameraPreset: 'pullOut',
          cameraStrength: 0.6,
          cameraTransitionDuration: 0.9,
          cameraTransitionEasing: 'smooth',
        },

        // ============================================================
        // 後半: 街で立ち止まって会話しているパート
        // ・背景は通常の1枚背景（town_far.png）固定表示
        // ・アオイは歩きモーション以外
        // ============================================================
        {
          id: 'stop_talk_1',
          speaker: 'アオイ',
          location: '街の広場・カフェ前',
          text: '「ここだよ！ ねこちゃんの看板のカフェ！ ここのアップルパイ、すっごく評判なんだって〜」',
          voiceUrl: '/voices/town_walk_cafe_1.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Excited.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'kirakira',
          },
          cameraZoom: 'medium',
          cameraStartAngle: 'front',
          cameraDistance: 1.2,
          cameraPreset: 'orbitLeftHalf',
          cameraStrength: 0.35,
        },
        {
          id: 'stop_talk_2',
          speaker: 'アオイ',
          location: '街の広場・カフェ前',
          text: '「もし急ぎの用事がないなら……ちょっと寄っていかない？ 一緒に食べよ！」',
          voiceUrl: '/voices/town_walk_cafe_2.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Acknowledging.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.15,
          cameraPreset: 'pushIn',
          cameraStrength: 0.4,
          choices: [
            {
              text: '「いいね、行こう！ 今日は俺がごちそうするよ」',
              flag: 'choice_treat',
              goto: 'stop_route_treat',
              effectText: 'yatta',
            },
            {
              text: '「もちろん！ アオイのおごりなら喜んで！」',
              flag: 'choice_ask',
              goto: 'stop_route_ask',
              effectText: 'doki',
            },
          ],
        },

        // --- ルートA: ごちそうする ---
        {
          id: 'stop_route_treat',
          speaker: 'アオイ',
          location: '街の広場・カフェ前',
          text: '「わぁ、本当！？ やったぁ〜！ ありがとう、優しい〜！ じゃあ一番大きいやつ頼んじゃお♪ 行こ！」',
          voiceUrl: '/voices/town_walk_treat.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Excited.fbx',
            expression: 'happy',
            expressionWeight: 1.0,
            faceTexture: '/textures/girl_face_blush.png',
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'yatta',
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.1,
          cameraPreset: 'punchIn',
          cameraStrength: 0.6,
          goto: 'ending_walk',
        },

        // --- ルートB: おごりなら ---
        {
          id: 'stop_route_ask',
          speaker: 'アオイ',
          location: '街の広場・カフェ前',
          conditions: ['choice_ask'],
          text: '「えーっ！？ なんで私が奢る前提なの〜！？ ……まぁ、半分こならいいけどねっ♪ 行こ！」',
          voiceUrl: '/voices/town_walk_ask.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Dismissing Gesture.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'doki',
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.1,
          cameraPreset: 'pushIn',
          cameraStrength: 0.5,
          goto: 'ending_walk',
        },

        // --- 共通エンディング ---
        {
          id: 'ending_walk',
          speaker: '',
          location: '街の広場・カフェ前',
          text: '―― 爽やかな風が吹き抜ける放課後の並木道。二人は並んでカフェの扉を開けた。 【シナリオ終了】',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Standing Idle.fbx',
            expression: 'relaxed',
            expressionWeight: 0.8,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'wide',
          cameraStartAngle: 'front',
          cameraDistance: 1.35,
          cameraPreset: 'pullOut',
          cameraStrength: 0.5,
          cameraTransitionDuration: 1.0,
          cameraTransitionEasing: 'smooth',
        },
      ],
    },
  ],
};

export const TOWN_WALK_SCENARIO_EN: ScenarioPackage = {
  id: 'town_walk',
  title: 'Walking with Aoi on the Avenue',
  bgmUrl: '/bgm/bgm.mp3',
  bgmVolume: 0.3,
  chapters: [
    {
      id: 'main',
      title: 'Avenue Walk',
      scenes: [
        {
          id: 'walk_1',
          speaker: 'Aoi',
          location: 'Tree-lined Avenue',
          text: '"Walking home together side by side like this... it has been quite a while, hasn\'t it?"',
          voiceUrl: '/voices/town_walk_1.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.85,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          cameraPreset: 'pushIn',
          cameraStrength: 0.2,
          cameraTransitionDuration: 0,
          cameraTransitionEasing: 'cut',
        },
        {
          id: 'walk_2',
          speaker: 'Aoi',
          location: 'Tree-lined Avenue',
          text: '"This avenue has such lovely town scenery, and the gentle breeze feels so refreshing!"',
          voiceUrl: '/voices/town_walk_2.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.95,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.88,
          cameraPreset: 'hold',
          cameraTransitionDuration: 0.7,
        },
        {
          id: 'walk_3',
          speaker: 'Aoi',
          location: 'Tree-lined Avenue',
          text: '"Hey, are you listening? ...Hehe, why are you staring at my face like that?"',
          voiceUrl: '/voices/town_walk_3.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0.12, 0, 0],
            rotationY: -0.25,
            effectText: 'doki',
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_extreme_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.82,
          cameraPreset: 'pushIn',
          cameraStrength: 0.5,
          choices: [
            {
              text: '"You looked so cheerful, I couldn\'t help but admire you."',
              flag: 'admire_her',
              goto: 'walk_route_admire',
              effectText: 'doki',
            },
            {
              text: '"I just remembered that a new cafe opened up ahead."',
              flag: 'talk_shop',
              goto: 'walk_route_shop',
              effectText: 'kirakira',
            },
          ],
        },
        {
          id: 'walk_route_admire',
          speaker: 'Aoi',
          location: 'Tree-lined Avenue',
          text: '"Come on! Saying something like that out of nowhere... you\'re making me blush!"',
          voiceUrl: '/voices/town_walk_admire.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            faceTexture: '/textures/girl_face_blush.png',
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          goto: 'walk_transition_stop',
        },
        {
          id: 'walk_route_shop',
          speaker: 'Aoi',
          location: 'Tree-lined Avenue',
          text: '"Oh, you knew about it too?! I was just about to bring that up!"',
          voiceUrl: '/voices/town_walk_shop.wav',
          avatar: {
            motion: '/animations/Walking.fbx',
            expression: 'relaxed',
            expressionWeight: 0.95,
            position: [0.12, 0, 0],
            rotationY: -0.22,
          },
          scrollingBackground: {
            enabled: true,
            textureUrl: '/textures/town_far.png',
            speed: 0.65,
            blur: 1.0,
            direction: 'left',
          },
          cameraZoom: 'speaker_close',
          cameraStartAngle: 'left',
          cameraDistance: 0.85,
          goto: 'walk_transition_stop',
        },
        {
          id: 'walk_transition_stop',
          speaker: 'Aoi',
          location: 'Town Square - Before Cafe',
          text: '"Look, look! Over there, that cute cat signboard... wait, let\'s stop here!"',
          voiceUrl: '/voices/town_walk_stop.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Standing Greeting.fbx',
            expression: 'relaxed',
            expressionWeight: 0.85,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'medium',
          cameraStartAngle: 'front',
          cameraDistance: 1.25,
          cameraPreset: 'pullOut',
          cameraStrength: 0.6,
          cameraTransitionDuration: 0.9,
          cameraTransitionEasing: 'smooth',
        },
        {
          id: 'stop_talk_1',
          speaker: 'Aoi',
          location: 'Town Square - Before Cafe',
          text: '"Right here! The cafe with the cat signboard! Their apple pie is supposedly super delicious!"',
          voiceUrl: '/voices/town_walk_cafe_1.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Excited.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'kirakira',
          },
          cameraZoom: 'medium',
          cameraStartAngle: 'front',
          cameraDistance: 1.2,
          cameraPreset: 'orbitLeftHalf',
          cameraStrength: 0.35,
        },
        {
          id: 'stop_talk_2',
          speaker: 'Aoi',
          location: 'Town Square - Before Cafe',
          text: '"If you\'re not in a hurry... want to drop by? Let\'s eat together!"',
          voiceUrl: '/voices/town_walk_cafe_2.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Acknowledging.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.15,
          cameraPreset: 'pushIn',
          cameraStrength: 0.4,
          choices: [
            {
              text: '"Sounds great, let\'s go! My treat today."',
              flag: 'choice_treat',
              goto: 'stop_route_treat',
              effectText: 'yatta',
            },
            {
              text: '"Sure! As long as you\'re paying, Aoi!"',
              flag: 'choice_ask',
              goto: 'stop_route_ask',
              effectText: 'doki',
            },
          ],
        },
        {
          id: 'stop_route_treat',
          speaker: 'Aoi',
          location: 'Town Square - Before Cafe',
          text: '"Really?! Yay! Thank you, you\'re so sweet! I\'m ordering the biggest slice! Let\'s go!"',
          voiceUrl: '/voices/town_walk_treat.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Excited.fbx',
            expression: 'happy',
            expressionWeight: 1.0,
            faceTexture: '/textures/girl_face_blush.png',
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'yatta',
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.1,
          cameraPreset: 'punchIn',
          cameraStrength: 0.6,
          goto: 'ending_walk',
        },
        {
          id: 'stop_route_ask',
          speaker: 'Aoi',
          location: 'Town Square - Before Cafe',
          conditions: ['choice_ask'],
          text: '"What?! Why are you assuming I\'m treating?! ...Well, I guess going half-and-half is fine! Let\'s go!"',
          voiceUrl: '/voices/town_walk_ask.wav',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Dismissing Gesture.fbx',
            expression: 'relaxed',
            expressionWeight: 0.9,
            position: [0, 0, 0],
            rotationY: 0,
            effectText: 'doki',
          },
          cameraZoom: 'speaker',
          cameraStartAngle: 'front',
          cameraDistance: 1.1,
          cameraPreset: 'pushIn',
          cameraStrength: 0.5,
          goto: 'ending_walk',
        },

        // --- Common Ending ---
        {
          id: 'ending_walk',
          speaker: '',
          location: 'Town Square - Before Cafe',
          text: '--- Under the gentle breeze of the after-school avenue, the two opened the cafe door side by side. [Scenario End]',
          background: '/textures/town_far.png',
          avatar: {
            motion: '/animations/Standing Idle.fbx',
            expression: 'relaxed',
            expressionWeight: 0.8,
            position: [0, 0, 0],
            rotationY: 0,
          },
          cameraZoom: 'wide',
          cameraStartAngle: 'front',
          cameraDistance: 1.35,
          cameraPreset: 'pullOut',
          cameraStrength: 0.5,
          cameraTransitionDuration: 1.0,
          cameraTransitionEasing: 'smooth',
        },
      ],
    },
  ],
};

export function getTownWalkScenario(lang: Language = getLanguage()): ScenarioPackage {
  return lang === 'en' ? TOWN_WALK_SCENARIO_EN : TOWN_WALK_SCENARIO_JA;
}
