import { ScenarioPackage } from './types';
import { Language, getLanguage } from '../i18n';
import { resolveAssetUrl } from '../utils/path';

export const TRIO_CONVERSATION_SCENARIO_JA: ScenarioPackage = {
  id: 'trio_chat',
  title: '放課後トライアングル〜アオイとエミリとあなた〜',
  characters: [
    {
      id: 'girl_01',
      character: resolveAssetUrl('/models/girl.vrm'),
      position: [-0.38, 0, -1.35],
      rotationY: 0.22,
    },
    {
      id: 'girl_02',
      character: resolveAssetUrl('/models/girl2.vrm'),
      position: [0.38, 0, -1.35],
      rotationY: -0.22,
    },
  ],
  bgmUrl: resolveAssetUrl('/bgm/bgm.mp3'),
  bgmVolume: 0.25,
  chapters: [
    {
      id: 'main',
      title: '放課後の作戦会議',
      scenes: [
        // Scene 1: アオイがあなたに話しかける（エミリはアオイを注視）
        {
          id: 'trio_intro_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '放課後の教室',
          scenePreset: 'evening_school',
          background: resolveAssetUrl('/textures/school-corridor-far.avif'),
          voiceUrl: resolveAssetUrl('/voices/trio_intro_1.wav'),
          text: '「ねえ……ちょっといいかな？ 放課後、急に引き留めちゃってごめんね」',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        // Scene 2: エミリがアオイにツッコミ（アオイもエミリを見る）
        {
          id: 'trio_intro_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_2.wav'),
          text: '「あーっ！ アオイずるい！ 私を置いて2人だけで内緒話しようとしてたでしょ〜！」',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.7,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'iraira',
            },
          },
        },
        // Scene 3: アオイがエミリに慌てて弁明（2人が見つめ合う）
        {
          id: 'trio_intro_3',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_3.wav'),
          text: '「ち、違うよエミリ！ 内緒話なんかじゃないってば。今度の週末、3人でどこか出かけないかって相談しようと思って……」',
          cameraPosition: [-0.02, 1.22, 0.20],
          cameraTarget: [-0.04, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              effectText: 'wanawana',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        // Scene 4: エミリがあなたに向き直り、同意を求める（アオイがエミリを見守る）
        {
          id: 'trio_intro_4',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_4.wav'),
          text: '「えっ、3人でお出かけ！？ やったぁ！ ……ねえねえ、あなたはどう？ 私たち2人と一緒に行くの、嫌じゃない？」',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        // Scene 5: 選択肢（2人同時にあなたにしっかり目線と首を向けて返事を待つ）
        {
          id: 'trio_choice',
          speaker: 'アオイ & エミリ',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_choice.wav'),
          text: '「どこに行きたい？ 3人で一緒に決めよっ！」',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.7,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
              headWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
              headWeight: 0.9,
            },
          },
          choices: [
            {
              text: '🍰 おしゃれなカフェで新作スイーツ巡り！',
              flag: 'choice_cafe',
              goto: 'route_cafe_1',
              effectText: 'yatta',
            },
            {
              text: '🌊 海が見える公園でのんびりピクニック！',
              flag: 'choice_picnic',
              goto: 'route_picnic_1',
              effectText: 'kirakira',
            },
            {
              text: '✨ 2人と一緒なら、どこへ行っても楽しいよ！',
              flag: 'choice_anywhere',
              goto: 'route_anywhere_1',
              effectText: 'doki',
            },
          ],
        },

        // -------------------------------------------------------------
        // ルート1: カフェ巡り
        // -------------------------------------------------------------
        {
          id: 'route_cafe_1',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_1.wav'),
          text: '「わぁっ、大賛成！ 駅前にできたカフェ、季節限定のいちごタルトがすっごく美味しいんだって！」',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        {
          id: 'route_cafe_2',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_2.wav'),
          text: '「もう、エミリはいつも甘いものばかり……でも、私もあそこの紅茶気になってたんだよね」',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_cafe_3',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_3.wav'),
          text: '「えへへ、じゃあ決まりね！ アオイにも半分分けてあげるから！」',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
            },
          },
        },

        // -------------------------------------------------------------
        // ルート2: ピクニック
        // -------------------------------------------------------------
        {
          id: 'route_picnic_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_1.wav'),
          text: '「海辺の公園……！ すごく素敵。潮風を浴びながらおしゃべりするの、楽しみだな」',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              effectText: 'kirakira',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_picnic_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_2.wav'),
          text: '「いいねいいね！ 私、お弁当にサンドイッチ作って持っていっちゃおうかな〜！」',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        {
          id: 'route_picnic_3',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_3.wav'),
          text: '「ふふっ、エミリのサンドイッチ、味見ならいつでも手伝うよ？ 一緒に作ろうか」',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },

        // -------------------------------------------------------------
        // ルート3: どこでも楽しい
        // -------------------------------------------------------------
        {
          id: 'route_anywhere_1',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_1.wav'),
          text: '「そんな風に言ってもらえるなんて……ふふっ、ありがとう。私もあなたと一緒ならどこでも嬉しいな」',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              effectText: 'doki',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_anywhere_2',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_2.wav'),
          text: '「きゃーっ！ さらっとそういうこと言っちゃうんだから〜！ アオイ、顔真っ赤になってるよ！」',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'doki',
            },
          },
        },
        {
          id: 'route_anywhere_3',
          speaker: 'アオイ',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_3.wav'),
          text: '「も、もうっ、からかわないでよエミリ！ ……でも、本当に嬉しいな」',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },

        // -------------------------------------------------------------
        // エンディング: 2人揃ってあなたへ呼びかけ
        // -------------------------------------------------------------
        {
          id: 'trio_ending',
          speaker: 'エミリ',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_ending.wav'),
          text: '「「それじゃあ今週末、楽しみにしてるね！ 約束だよ！」」 ―― 3人の特別な放課後会議が幕を閉じた。【シナリオ終了】',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.7,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'kirakira',
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
            },
          },
        },
      ],
    },
  ],
};

export const TRIO_CONVERSATION_SCENARIO_EN: ScenarioPackage = {
  id: 'trio_chat',
  title: 'After-School Triangle: Aoi, Emiri, and You',
  characters: [
    {
      id: 'girl_01',
      character: resolveAssetUrl('/models/girl.vrm'),
      position: [-0.38, 0, -1.35],
      rotationY: 0.22,
    },
    {
      id: 'girl_02',
      character: resolveAssetUrl('/models/girl2.vrm'),
      position: [0.38, 0, -1.35],
      rotationY: -0.22,
    },
  ],
  bgmUrl: resolveAssetUrl('/bgm/bgm.mp3'),
  bgmVolume: 0.25,
  chapters: [
    {
      id: 'main',
      title: 'After-School Strategy Meeting',
      scenes: [
        {
          id: 'trio_intro_1',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          scenePreset: 'evening_school',
          background: resolveAssetUrl('/textures/school-corridor-far.avif'),
          voiceUrl: resolveAssetUrl('/voices/trio_intro_1.wav'),
          text: '"Hey... do you have a moment? Sorry to keep you suddenly after school."',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'trio_intro_2',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_2.wav'),
          text: '"Aah! Not fair, Aoi! Were you trying to have a secret talk alone without me~?"',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'surprised',
              expressionWeight: 0.7,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'iraira',
            },
          },
        },
        {
          id: 'trio_intro_3',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_3.wav'),
          text: '"N-No, Emiri! It\'s not a secret at all. I was just hoping to ask if the three of us could hang out together this weekend..."',
          cameraPosition: [-0.02, 1.22, 0.20],
          cameraTarget: [-0.04, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
              effectText: 'wanawana',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'trio_intro_4',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_intro_4.wav'),
          text: '"Wait, the three of us together!? Yay! ...Hey, what do you think? You wouldn\'t mind joining us two, right?"',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        {
          id: 'trio_choice',
          speaker: 'Aoi & Emiri',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_choice.wav'),
          text: '"Where should we go? Let\'s choose together!"',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.7,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
              headWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
              headWeight: 0.9,
            },
          },
          choices: [
            {
              text: '🍰 Let\'s explore sweet treats at a lovely cafe!',
              flag: 'choice_cafe',
              goto: 'route_cafe_1',
              effectText: 'yatta',
            },
            {
              text: '🌊 A relaxing picnic at the seaside park!',
              flag: 'choice_picnic',
              goto: 'route_picnic_1',
              effectText: 'kirakira',
            },
            {
              text: '✨ Anywhere is wonderful as long as I\'m with you two!',
              flag: 'choice_anywhere',
              goto: 'route_anywhere_1',
              effectText: 'doki',
            },
          ],
        },

        // Route 1: Cafe
        {
          id: 'route_cafe_1',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_1.wav'),
          text: '"Awesome! The new cafe by the station has incredible seasonal strawberry tarts!"',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        {
          id: 'route_cafe_2',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_2.wav'),
          text: '"Oh Emiri, you always go for sweets... But actually, I was curious about their tea selection too."',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_cafe_3',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_cafe_3.wav'),
          text: '"Hehe, then it\'s settled! I\'ll share a slice with you, Aoi!"',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
            },
          },
        },

        // Route 2: Picnic
        {
          id: 'route_picnic_1',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_1.wav'),
          text: '"The seaside park...! That sounds so nice. Enjoying the breeze and talking sounds lovely."',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              effectText: 'kirakira',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_picnic_2',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_2.wav'),
          text: '"Great idea! Maybe I\'ll pack some homemade sandwiches for all of us~!"',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'yatta',
            },
          },
        },
        {
          id: 'route_picnic_3',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_picnic_3.wav'),
          text: '"Hehe, I\'ll happily help you taste-test beforehand! Shall we make them together?"',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },

        // Route 3: Anywhere
        {
          id: 'route_anywhere_1',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_1.wav'),
          text: '"To hear you say that... hehe, thank you. Anywhere with you makes me so happy too."',
          cameraPosition: [-0.04, 1.22, 0.20],
          cameraTarget: [-0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Dismissing Gesture.fbx'),
              expression: 'relaxed',
              expressionWeight: 1.0,
              effectText: 'doki',
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },
        {
          id: 'route_anywhere_2',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_2.wav'),
          text: '"Kyaa~! You say that with such a straight face! Look, Aoi\'s face is totally red!"',
          cameraPosition: [0.04, 1.22, 0.20],
          cameraTarget: [0.08, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'doki',
            },
          },
        },
        {
          id: 'route_anywhere_3',
          speaker: 'Aoi',
          speakerCharacterId: 'girl_01',
          dialogueTarget: 'partner',
          location: 'Classroom at Twilight',
          voiceUrl: resolveAssetUrl('/voices/trio_anywhere_3.wav'),
          text: '"S-Stop teasing, Emiri! ...Though, I\'m honestly really glad."',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.6,
          cameraPreset: 'hold',
          goto: 'trio_ending',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Acknowledging.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.9,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Standing Idle.fbx'),
              expression: 'relaxed',
              expressionWeight: 0.8,
            },
          },
        },

        // Ending
        {
          id: 'trio_ending',
          speaker: 'Emiri',
          speakerCharacterId: 'girl_02',
          dialogueTarget: 'player',
          location: '放課後の教室',
          voiceUrl: resolveAssetUrl('/voices/trio_ending.wav'),
          text: '"「それじゃあ今週末、楽しみにしてるね！ 約束だよ！」" ―― 3人の特別な放課後会議が幕を閉じた。【シナリオ終了】',
          cameraPosition: [0, 1.22, 0.20],
          cameraTarget: [0, 1.22, -1.35],
          cameraZoom: 'wide',
          cameraTransitionDuration: 0.7,
          cameraPreset: 'hold',
          avatars: {
            girl_01: {
              motion: resolveAssetUrl('/animations/Standing Greeting.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              effectText: 'kirakira',
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
            },
            girl_02: {
              motion: resolveAssetUrl('/animations/Excited.fbx'),
              expression: 'happy',
              expressionWeight: 1.0,
              lookAtTarget: 'player',
              shallowHeadAngle: false,
              headMaxYaw: 0.8,
            },
          },
        },
      ],
    },
  ],
};

export function getTrioConversationScenario(language: Language = getLanguage()): ScenarioPackage {
  return language === 'ja' ? TRIO_CONVERSATION_SCENARIO_JA : TRIO_CONVERSATION_SCENARIO_EN;
}
