import { resolveAssetUrl } from '../utils/path';
import type { AvatarConfig } from '../Config';

export type ScenePresetId =
  | 'morning_park'
  | 'noon_park'
  | 'evening_park'
  | 'morning_school'
  | 'noon_school'
  | 'evening_school'
  | 'bright_indoor'
  | 'dark_indoor'
  | 'morning_outdoor'
  | 'noon_outdoor'
  | 'evening_outdoor';

export interface ScenePresetData {
  id: ScenePresetId;
  name: string;
  category: 'outdoor' | 'indoor';
  description: string;
  environment: AvatarConfig['environment'];
  lighting: AvatarConfig['lighting'];
  postProcessing: AvatarConfig['postProcessing'];
  materials?: Partial<AvatarConfig['materials']>;
  wind?: Partial<AvatarConfig['wind']>;
}

export const SCENE_PRESETS: Record<string, ScenePresetData> = {
  // ====================================================
  // 屋外 (Outdoor) - 公園 (Park) 3パターン
  // ====================================================

  // 1. 朝 × 公園 (Morning Park)
  morning_park: {
    id: 'morning_park',
    name: '朝・公園',
    category: 'outdoor',
    description: '青空と強い太陽光、抜けの良い昼光サンシャフトと華やかなアニメフレア（多層背景）',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/modern-park-far.jpg'),
      backgroundColor: '#ffffff',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: true,
      midgroundImageUrl: resolveAssetUrl('/textures/modern-park-mid.jpg'),
      midgroundPosition: { x: 0, y: 1.35, z: -0.25 },
      midgroundScale: 1.15,
      midgroundOpacity: 1.0,
      farFogEnabled: true,
      farFogColor: '#ffffff',
      farFogIntensity: 0.24,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffb8b8',
        intensity: 0.35,
      },
      directional: {
        color: '#ffffff',
        intensity: 2.6,
        posX: 4.1,
        posY: 2.5,
        posZ: 2.0,
      },
      rim: {
        enabled: false,
        color: '#dde8ff',
        intensity: 0.05,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 4.0,
        threshold: 0.15,
        intensity: 0.8,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: 3.2,
          y: 4.3,
          z: -3.8,
        },
        exposure: 0.24,
        decay: 0.91,
        density: 0.8,
        weight: 0.24,
        color: '#fff2db',
        shimmer: 0.4,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.25,
        sunColor: '#fff8ee',
        glowIntensity: 1.15,
        starburstIntensity: 1.05,
        anamorphicIntensity: 1.2,
        ghostIntensity: 0.85,
        haloIntensity: 0.9,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.09,
        radius: 0.16,
        threshold: 0.85,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#5471f2',
        highlightTint: '#ffffff',
        strength: 0.5,
        contrast: 0.13,
        gamma: 1.0,
      },
      saturation: 0.26,
      brightness: 0.0,
      contrast: 0.0,
    },
    wind: {
      enabled: true,
    },
  },

  // 2. 昼 × 公園 (Noon Park)
  noon_park: {
    id: 'noon_park',
    name: '昼・公園',
    category: 'outdoor',
    description: '爽やかな朝の斜光、澄んだ大気フォグ、淡い朝焼けサンシャフトとシャープなフレア（多層背景）',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/modern-park-far.jpg'),
      backgroundColor: '#ffffff',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: true,
      midgroundImageUrl: resolveAssetUrl('/textures/modern-park-mid.jpg'),
      midgroundPosition: { x: 0, y: 1.35, z: -0.25 },
      midgroundScale: 1.15,
      midgroundOpacity: 1.0,
      farFogEnabled: true,
      farFogColor: '#e0ebff',
      farFogIntensity: 0.32,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffebeb',
        intensity: 0.45,
      },
      directional: {
        color: '#ffffff',
        intensity: 2,
        posX: -2.2,
        posY: 3.2,
        posZ: 3,
      },
      rim: {
        enabled: true,
        color: '#ffe8d6',
        intensity: 0.25,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 4.2,
        threshold: 0.15,
        intensity: 0.85,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: -1.3,
          y: 6.4,
          z: -7.6,
        },
        exposure: 0.16,
        decay: 0.86,
        density: 0.5,
        weight: 0.44,
        color: '#ffe8c2',
        shimmer: 0.4,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.1,
        sunColor: '#fff5e4',
        glowIntensity: 0.35,
        starburstIntensity: 0.85,
        anamorphicIntensity: 0.35,
        ghostIntensity: 0.5,
        haloIntensity: 0.45,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.04,
        radius: 0.14,
        threshold: 0.84,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#4a5596',
        highlightTint: '#fff7ec',
        strength: 0.45,
        contrast: 0.12,
        gamma: 1.0,
      },
      saturation: 0.4,
      brightness: 0.04,
      contrast: 0.02,
    },
    wind: {
      enabled: true,
    },
  },

  // 3. 夕方 × 公園 (Evening Park - デフォルト)
  evening_park: {
    id: 'evening_park',
    name: '夕方・公園',
    category: 'outdoor',
    description: 'ドラマチックな茜色の夕日、西日のサンシャフトと夕焼けレンズフレア（多層背景）',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/modern-park-far.jpg'),
      backgroundColor: '#2b101d',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: true,
      midgroundImageUrl: resolveAssetUrl('/textures/modern-park-mid.jpg'),
      midgroundPosition: {
        x: 0,
        y: 1.35,
        z: -0.25,
      },
      midgroundScale: 1.15,
      midgroundOpacity: 1.0,
      farFogEnabled: true,
      farFogColor: '#ff7e4d',
      farFogIntensity: 0.08,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#3e407a',
        intensity: 0.5,
      },
      directional: {
        color: '#fffbf0',
        intensity: 1.8,
        posX: -3.7,
        posY: 0.8,
        posZ: 0.7,
      },
      rim: {
        enabled: true,
        color: '#ffaa60',
        intensity: 0.3,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 3.5,
        threshold: 0.12,
        intensity: 1.0,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: -5.5,
          y: 1.6,
          z: -3.5,
        },
        exposure: 0.36,
        decay: 0.83,
        density: 0.5,
        weight: 0.48,
        color: '#ff7826',
        shimmer: 0.25,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.05,
        sunColor: '#ff6222',
        glowIntensity: 1.15,
        starburstIntensity: 1.05,
        anamorphicIntensity: 0.95,
        ghostIntensity: 0.95,
        haloIntensity: 0.3,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.15,
        radius: 0.22,
        threshold: 0.78,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#391752',
        highlightTint: '#ffad70',
        strength: 0.65,
        contrast: 0.18,
        gamma: 0.95,
      },
      saturation: 0.26,
      brightness: -0.04,
      contrast: 0.08,
    },
    wind: {
      enabled: true,
    },
  },

  // ====================================================
  // 屋外 (Outdoor) - 校門 (School Gate) 3パターン
  // ====================================================

  // 4. 朝 × 校門 (Morning School Gate)
  morning_school: {
    id: 'morning_school',
    name: '朝・校門',
    category: 'outdoor',
    description: '澄んだ青空と朝の爽やかな日差し、校門前のアニメライティング',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/school-gate-far.jpeg'),
      backgroundColor: '#ffffff',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: false,
      midgroundImageUrl: undefined,
      farFogEnabled: true,
      farFogColor: '#ffffff',
      farFogIntensity: 0.15,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffb8b8',
        intensity: 0.35,
      },
      directional: {
        color: '#ffffff',
        intensity: 2.6,
        posX: 4.1,
        posY: 2.5,
        posZ: 2.0,
      },
      rim: {
        enabled: false,
        color: '#dde8ff',
        intensity: 0.05,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 4.0,
        threshold: 0.15,
        intensity: 0.8,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: 3.2,
          y: 4.3,
          z: -3.8,
        },
        exposure: 0.24,
        decay: 0.91,
        density: 0.8,
        weight: 0.24,
        color: '#fff2db',
        shimmer: 0.4,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.25,
        sunColor: '#fff8ee',
        glowIntensity: 1.15,
        starburstIntensity: 1.05,
        anamorphicIntensity: 1.2,
        ghostIntensity: 0.85,
        haloIntensity: 0.9,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.09,
        radius: 0.16,
        threshold: 0.85,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#5471f2',
        highlightTint: '#ffffff',
        strength: 0.5,
        contrast: 0.13,
        gamma: 1.0,
      },
      saturation: 0.26,
      brightness: 0.0,
      contrast: 0.0,
    },
    wind: {
      enabled: true,
    },
  },

  // 5. 昼 × 校門 (Noon School Gate)
  noon_school: {
    id: 'noon_school',
    name: '昼・校門',
    category: 'outdoor',
    description: '鮮やかな晴天の昼光、抜けの良い大気とシャープなフレア',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/school-gate-far.jpeg'),
      backgroundColor: '#ffffff',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: false,
      midgroundImageUrl: undefined,
      farFogEnabled: true,
      farFogColor: '#e0ebff',
      farFogIntensity: 0.2,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffebeb',
        intensity: 0.45,
      },
      directional: {
        color: '#ffffff',
        intensity: 2,
        posX: -2.2,
        posY: 3.2,
        posZ: 3,
      },
      rim: {
        enabled: true,
        color: '#ffe8d6',
        intensity: 0.25,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 4.2,
        threshold: 0.15,
        intensity: 0.85,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: -1.3,
          y: 6.4,
          z: -7.6,
        },
        exposure: 0.16,
        decay: 0.86,
        density: 0.5,
        weight: 0.44,
        color: '#ffe8c2',
        shimmer: 0.4,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.1,
        sunColor: '#fff5e4',
        glowIntensity: 0.35,
        starburstIntensity: 0.85,
        anamorphicIntensity: 0.35,
        ghostIntensity: 0.5,
        haloIntensity: 0.45,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.04,
        radius: 0.14,
        threshold: 0.84,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#4a5596',
        highlightTint: '#fff7ec',
        strength: 0.45,
        contrast: 0.12,
        gamma: 1.0,
      },
      saturation: 0.4,
      brightness: 0.04,
      contrast: 0.02,
    },
    wind: {
      enabled: true,
    },
  },

  // 6. 夕方 × 校門 (Evening School Gate)
  evening_school: {
    id: 'evening_school',
    name: '夕方・校門',
    category: 'outdoor',
    description: '放課後のドラマチックな茜色夕日、西日のサンシャフトと夕焼けフレア',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/school-gate-far.jpeg'),
      backgroundColor: '#2b101d',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: false,
      midgroundImageUrl: undefined,
      farFogEnabled: true,
      farFogColor: '#ff7e4d',
      farFogIntensity: 0.22,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#3e407a',
        intensity: 0.5,
      },
      directional: {
        color: '#fffbf0',
        intensity: 1.8,
        posX: -3.7,
        posY: 0.8,
        posZ: 0.7,
      },
      rim: {
        enabled: true,
        color: '#ffaa60',
        intensity: 0.3,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 3.5,
        threshold: 0.12,
        intensity: 1.0,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: -5.5,
          y: 1.6,
          z: -3.5,
        },
        exposure: 0.36,
        decay: 0.83,
        density: 0.5,
        weight: 0.48,
        color: '#ff7826',
        shimmer: 0.25,
      },
      lensFlare: {
        enabled: true,
        sunSize: 1.05,
        sunColor: '#ff6222',
        glowIntensity: 1.15,
        starburstIntensity: 1.05,
        anamorphicIntensity: 0.95,
        ghostIntensity: 0.95,
        haloIntensity: 0.3,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.15,
        radius: 0.22,
        threshold: 0.78,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#391752',
        highlightTint: '#ffad70',
        strength: 0.65,
        contrast: 0.18,
        gamma: 0.95,
      },
      saturation: 0.26,
      brightness: -0.04,
      contrast: 0.08,
    },
    wind: {
      enabled: true,
    },
  },

  // ====================================================
  // 室内 (Indoor) 2パターン（明るい・暗い）
  // ====================================================

  // 4. 明るい × 室内 (Bright Indoor)
  bright_indoor: {
    id: 'bright_indoor',
    name: '明るい・室内',
    category: 'indoor',
    description: '窓から光が差し込む明るい教室、自然で柔らかなアニメ発色（フレア・光条OFF）',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: true,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/school-corridor-far.jpg'),
      backgroundColor: '#ffffff',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: false,
      midgroundImageUrl: undefined,
      midgroundPosition: { x: 0, y: 1.35, z: -0.25 },
      midgroundScale: 1.15,
      midgroundOpacity: 1.0,
      farFogEnabled: false,
      farFogColor: '#ffffff',
      farFogIntensity: 0.0,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffebeb',
        intensity: 0.65,
      },
      directional: {
        color: '#ffffff',
        intensity: 2.2,
        posX: -3.5,
        posY: 2.8,
        posZ: 1.8,
      },
      rim: {
        enabled: true,
        color: '#ffebeb',
        intensity: 0.2,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 4.2,
        threshold: 0.18,
        intensity: 0.6,
      },
      sunShafts: {
        enabled: false,
        followDirectionalLight: false,
        sunPosition: { x: 0, y: 5, z: 0 },
        exposure: 0,
        decay: 0.9,
        density: 0.5,
        weight: 0.1,
        color: '#ffffff',
        shimmer: 0,
      },
      lensFlare: {
        enabled: false,
        sunSize: 0.8,
        sunColor: '#ffffff',
        glowIntensity: 0,
        starburstIntensity: 0,
        anamorphicIntensity: 0,
        ghostIntensity: 0,
        haloIntensity: 0,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: true,
        strength: 0.05,
        radius: 0.12,
        threshold: 0.9,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#505068',
        highlightTint: '#ffffff',
        strength: 0.25,
        contrast: 0.08,
        gamma: 1.0,
      },
      saturation: 0.4,
      brightness: 0.0,
      contrast: 0.0,
    },
    wind: {
      enabled: false,
    },
  },

  // 5. 暗い × 室内 (Dark Indoor)
  dark_indoor: {
    id: 'dark_indoor',
    name: '暗い・室内',
    category: 'indoor',
    description: '窓からの夜光と落ち着いた間接照明、エモーショナルな夜間教室・室内',
    materials: {
      body: {
        color: '#fffafa',
        shadowHueShift: 0.02,
        shadowLightnessFactor: 0.16,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 5,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.1,
        outlineWidthFactor: 0.001,
      },
      hair: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#ffffff',
        parametricRimFresnelPowerFactor: 0,
        parametricRimLiftFactor: 0.1,
        rimLightingMixFactor: 0.2,
        outlineWidthFactor: 0.0008,
      },
      cloth: {
        color: '#ffffff',
        shadowHueShift: 0.03,
        shadowLightnessFactor: 0.2,
        shadingToonyFactor: 1,
        shadingShiftFactor: -0.05,
        giEqualizationFactor: 0.9,
        rimEnabled: false,
        rimColor: '#202942',
        parametricRimFresnelPowerFactor: 4,
        parametricRimLiftFactor: 0.02,
        rimLightingMixFactor: 1,
        outlineWidthFactor: 0.001,
      },
    },
    environment: {
      showBackgroundImage: true,
      backgroundImageUrl: resolveAssetUrl('/textures/school-corridor-far.jpg'),
      backgroundColor: '#181824',
      showFloor: false,
      floorColor: '#ffffff',
      showMidground: false,
      midgroundImageUrl: undefined,
      midgroundPosition: {
        x: 0,
        y: 1.35,
        z: -0.25,
      },
      midgroundScale: 1.15,
      midgroundOpacity: 1.0,
      farFogEnabled: false,
      farFogColor: '#303048',
      farFogIntensity: 0.0,
    },
    lighting: {
      castShadows: false,
      ambient: {
        color: '#ffebeb',
        intensity: 0.3,
      },
      directional: {
        color: '#b7cdf0',
        intensity: 2.5,
        posX: -3.5,
        posY: 2.2,
        posZ: 1.5,
      },
      rim: {
        enabled: false,
        color: '#8fa8db',
        intensity: 0.22,
        posX: 0,
        posY: 1.5,
        posZ: 2.5,
      },
      depthRim: {
        enabled: true,
        power: 3.8,
        threshold: 0.15,
        intensity: 0.75,
      },
      sunShafts: {
        enabled: true,
        followDirectionalLight: false,
        sunPosition: {
          x: -3.5,
          y: 2.2,
          z: -2.0,
        },
        exposure: 0.1,
        decay: 0.86,
        density: 0.55,
        weight: 0.18,
        color: '#7898d0',
        shimmer: 0.2,
      },
      lensFlare: {
        enabled: false,
        sunSize: 0.8,
        sunColor: '#8ca8db',
        glowIntensity: 0.3,
        starburstIntensity: 0.2,
        anamorphicIntensity: 0.2,
        ghostIntensity: 0.2,
        haloIntensity: 0.2,
      },
    },
    postProcessing: {
      toneMappingMode: 'None',
      toneMappingExposure: 1.0,
      antialiasing: {
        msaaSamples: 4,
        smaa: true,
      },
      bloom: {
        enabled: false,
        strength: 0.12,
        radius: 0.2,
        threshold: 0.75,
      },
      colorGrading: {
        enabled: true,
        shadowTint: '#1c1c30',
        highlightTint: '#c8d8f0',
        strength: 0.8,
        contrast: 0.16,
        gamma: 0.96,
      },
      saturation: 0.18,
      brightness: -0.3,
      contrast: -0.09,
    },
    wind: {
      enabled: false,
    },
  },
};

// Aliases for outdoor presets
SCENE_PRESETS.morning_outdoor = SCENE_PRESETS.morning_park;
SCENE_PRESETS.noon_outdoor = SCENE_PRESETS.noon_park;
SCENE_PRESETS.evening_outdoor = SCENE_PRESETS.evening_park;

/**
 * Helper to get a preset given preset ID
 */
export function getScenePreset(presetId: ScenePresetId): ScenePresetData {
  return SCENE_PRESETS[presetId] || SCENE_PRESETS.evening_park;
}
