import { EffectPresetName, EffectTextPreset } from './types';

export const EFFECT_TEXT_PRESETS: Record<EffectPresetName, EffectTextPreset> = {
  wanawana: {
    name: 'wanawana',
    spawnMode: 'surround',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#ff8ae2', '#9c27b0'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 14,
      outerStrokeColor: '#2b0938',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(30, 5, 45, 0.85)',
      shadowOffset: { x: 5, y: 7 },
      shadowBlur: 0,
      decorations: ['sweat', 'spikes'],
      decorationColor: '#ba68c8',
      charJitter: {
        rotationRange: 0.08,
        offsetYRange: 3,
        scaleRange: 0.05,
      },
      slant: -3,
      firstCharScale: 1.22,
      splitRepeatTilt: true,
      halfTiltRange: 0.14,
    },
    animations: ['pop', 'shake'],
    defaultDuration: Infinity,
    defaultScale: 0.34,
    defaultOffset: { x: 0, y: 0.04, z: 0.04 },
    shakeIntensity: {
      position: 0.006,
      rotation: 0.035,
      frequency: 9, // Subtle nervous comic shudder
    },
    streamConfig: {
      phrase: 'ワナ',
    },
  },

  iraira: {
    name: 'iraira',
    spawnMode: 'surround',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#ffe600', '#ff1744'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 14,
      outerStrokeColor: '#4a0000',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(50, 0, 0, 0.9)',
      shadowOffset: { x: 6, y: 8 },
      shadowBlur: 0,
      decorations: ['anger', 'spikes'],
      decorationColor: '#ff1744',
      charJitter: {
        rotationRange: 0.09,
        offsetYRange: 4,
        scaleRange: 0.06,
      },
      slant: -4,
      firstCharScale: 1.22,
      splitRepeatTilt: true,
      halfTiltRange: 0.15,
    },
    animations: ['pop', 'shake'],
    defaultDuration: Infinity,
    defaultScale: 0.35,
    defaultOffset: { x: 0, y: 0.04, z: 0.04 },
    shakeIntensity: {
      position: 0.007,
      rotation: 0.04,
      frequency: 8, // Calm simmering vibration
    },
    streamConfig: {
      phrase: 'イラ',
    },
  },

  doki: {
    name: 'doki',
    spawnMode: 'stream',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#ff9ebb', '#e91e63'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 14,
      outerStrokeColor: '#880e4f',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(136, 14, 79, 0.8)',
      shadowOffset: { x: 5, y: 6 },
      shadowBlur: 0,
      decorations: ['sparkle'],
      decorationColor: '#ff4081',
      charJitter: {
        rotationRange: 0.1,
        offsetYRange: 6,
        scaleRange: 0.08,
      },
      slant: -4,
    },
    animations: ['pop', 'pulse', 'rise', 'fadeOut'],
    defaultDuration: 2.0,
    defaultScale: 0.38,
    defaultOffset: { x: 0, y: -0.02, z: 0.04 },
    riseSpeed: 0.16,
    streamConfig: {
      phrase: 'ドキ',
      count: Infinity,
      interval: 0.52,
      spreadX: 0.18, // Tightly hugged near chest/neck
      riseSpeed: 0.16,
      particleDuration: 1.9,
      particleScale: 0.38,
    },
  },

  gaan: {
    name: 'gaan',
    spawnMode: 'single',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#80d8ff', '#1a237e'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 14,
      outerStrokeColor: '#0b1033',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(10, 15, 50, 0.9)',
      shadowOffset: { x: 4, y: 8 },
      shadowBlur: 0,
      decorations: ['shockLines', 'sweat'],
      decorationColor: '#4fc3f7',
      charJitter: {
        rotationRange: 0.06,
        offsetYRange: 4,
        scaleRange: 0.05,
      },
      slant: 4,
    },
    animations: ['pop', 'drop', 'fadeOut'],
    defaultDuration: 2.3,
    defaultScale: 0.70,
    defaultOffset: { x: 0, y: 0.22, z: 0.04 }, // Closely right above the forehead
    dropSpeed: 0.08,
  },

  shiin: {
    name: 'shiin',
    spawnMode: 'single',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#e2e8f0', '#64748b'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 12,
      outerStrokeColor: '#1e293b',
      outerStrokeWidth: 6,
      shadowColor: 'rgba(30, 41, 59, 0.7)',
      shadowOffset: { x: 4, y: 4 },
      shadowBlur: 0,
      decorations: ['dots'],
      decorationColor: '#94a3b8',
      charJitter: {
        rotationRange: 0.04,
        offsetYRange: 2,
        scaleRange: 0.03,
      },
      slant: 0,
    },
    animations: ['float', 'fadeOut'],
    defaultDuration: 2.5,
    defaultScale: 0.62,
    defaultOffset: { x: 0, y: 0.20, z: 0 }, // Closely right above the head
    floatParams: {
      speed: 1.6,
      height: 0.03,
    },
  },

  kirakira: {
    name: 'kirakira',
    spawnMode: 'single',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#fff9a6', '#ff4081'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 16,
      outerStrokeColor: '#c2185b',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(136, 14, 79, 0.8)',
      shadowOffset: { x: 6, y: 6 },
      shadowBlur: 0,
      decorations: ['sparkle'],
      decorationColor: '#ffd700',
      charJitter: {
        rotationRange: 0.12,
        offsetYRange: 7,
        scaleRange: 0.1,
      },
      slant: -5,
    },
    animations: ['pop', 'float', 'spinSmall', 'fadeOut'],
    defaultDuration: 2.2,
    defaultScale: 0.70,
    defaultOffset: { x: 0, y: 0.22, z: 0.04 }, // Closely right above the head
    floatParams: {
      speed: 3.2,
      height: 0.04,
    },
  },

  biku: {
    name: 'biku',
    spawnMode: 'single',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#ffffff', '#ffeb3b'],
      gradientDirection: 'vertical',
      strokeColor: '#000000',
      strokeWidth: 16,
      outerStrokeColor: '#ff6f00',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowOffset: { x: 6, y: 7 },
      shadowBlur: 0,
      decorations: ['exclamation', 'spikes'],
      decorationColor: '#ffeb3b',
      charJitter: {
        rotationRange: 0.2,
        offsetYRange: 10,
        scaleRange: 0.14,
      },
      slant: -8,
    },
    animations: ['pop', 'shake', 'fadeOut'],
    defaultDuration: 1.6,
    defaultScale: 0.72,
    defaultOffset: { x: 0, y: 0.22, z: 0.04 }, // Closely right above the head
    shakeIntensity: {
      position: 0.03,
      rotation: 0.2,
      frequency: 38,
    },
  },

  yatta: {
    name: 'yatta',
    spawnMode: 'single',
    style: {
      fontFamily: '"Mochiy Pop One", "M PLUS Rounded 1c", "Hiragino Kaku Gothic ProN", "Meiryo", "Arial Black", sans-serif',
      fontWeight: '900',
      textColor: ['#fff176', '#ff5722'],
      gradientDirection: 'vertical',
      strokeColor: '#ffffff',
      strokeWidth: 16,
      outerStrokeColor: '#bf360c',
      outerStrokeWidth: 8,
      shadowColor: 'rgba(191, 54, 12, 0.85)',
      shadowOffset: { x: 5, y: 7 },
      shadowBlur: 0,
      decorations: ['sparkle', 'exclamation'],
      decorationColor: '#ffd600',
      charJitter: {
        rotationRange: 0.14,
        offsetYRange: 8,
        scaleRange: 0.1,
      },
      slant: -6,
    },
    animations: ['pop', 'pulse', 'float', 'fadeOut'],
    defaultDuration: 2.4,
    defaultScale: 0.75,
    defaultOffset: { x: 0, y: 0.24, z: 0.04 },
    floatParams: {
      speed: 3.5,
      height: 0.04,
    },
  },
};
